name: dynabeat
description: A new Flutter project.



publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  cached_network_image: ^3.2.3
  iconsax: ^0.0.8
  audioplayers: ^1.1.1
  audio_video_progress_bar: ^0.11.0
  just_audio:
  marquee:
  flutter_spinkit: ^5.1.0
  google_nav_bar: ^5.0.6
  firebase_core:



dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:

  
  
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/GothamMedium.ttf
        - asset: assets/fonts/GothamLight.ttf
          weight: 400
        - asset: assets/fonts/GothamBold.ttf
          weight: 600
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/logo/
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
